version: "3.9"

services:
  db:
    image: postgres
    container_name: notes_db
    volumes:
      - data_notes:/var/lib/postgresql/data/
    restart: always
    env_file:
      - .env
    ports:
    - "5433:5432"
  
volumes:
  data_notes: