version: "3.9"

services:

  api_gateway:
    build: .
    container_name: api_gateway
    command: "uvicorn app.cmd.main:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - "127.0.0.1:8000:8000"