version: "3.9"

services:

  # auth_service:
  #   build: .
  #   container_name: auth_service
  #   command: ["./auth_service"]
  #   ports:
  #     - 10001:10001
  #   networks:
  #     - mynet

  db_auth:
    image: postgres
    container_name: db_auth
    volumes:
      - data_auth:/var/lib/postgresql/data/
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - mynet

  redis:
    image: redis
    container_name: redis
    restart: always
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - mynet

volumes:
  data_auth:

networks:
  mynet:
    driver: bridge