version: "3.9"

services:
  db:
    image: postgres
    container_name: app_db
    volumes:
      - df:/var/lib/postgresql/data/
    restart: always
    env_file:
      - .env
    ports:
    - "5432:5432"
  
volumes:
  df: