"""empty message

Revision ID: a0b32c6457a5
Revises: a5cbead2d795
Create Date: 2024-05-03 14:53:26.193185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0b32c6457a5'
down_revision = 'a5cbead2d795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
