"""empty message

Revision ID: a5cbead2d795
Revises: c3b296f5c083
Create Date: 2024-05-03 14:49:09.804363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a5cbead2d795'
down_revision = 'c3b296f5c083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('user_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'user_uuid')
    # ### end Alembic commands ###
