is_debug: true
env: "local"

jwt_secret: $3cr3t

bind_ip: 0.0.0.0
port: ":10001"

db:
  username: "postgres"
  host: "db"
  port: "5432"
  dbname: "postgres"
  sslmode: "disable"
  password: "postgres"
