is_debug: true
env: "local"

jwt_secret: $3cr3t

access_tokenTTL: 120
refresh_tokenTTL: 43200 #30 days

bind_ip: 0.0.0.0
port: ":10001"

storage:
  username: "postgres"
  host: "localhost"
  port: "5432"
  dbname: "postgres"
  sslmode: "disable"
  password: "postgres"