# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notes.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bnotes.proto\x12\x05notes\"B\n\x11\x43reateNoteRequest\x12\x10\n\x08userUUID\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t\"&\n\x12\x43reateNoteResponse\x12\x10\n\x08noteUUID\x18\x01 \x01(\t\"\"\n\x0eGetNoteRequest\x12\x10\n\x08noteUUID\x18\x01 \x01(\t\"z\n\x0fGetNoteResponse\x12\x10\n\x08noteUUID\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t\x12\x16\n\tupdate_at\x18\x04 \x01(\x02H\x00\x88\x01\x01\x12\x12\n\ncreated_at\x18\x05 \x01(\x02\x42\x0c\n\n_update_at\"\x15\n\x13GetListNotesRequest\"=\n\x14GetListNotesResponse\x12%\n\x05notes\x18\x01 \x03(\x0b\x32\x16.notes.GetNoteResponse2\xc8\x01\n\x04Note\x12\x41\n\nCreateNote\x12\x18.notes.CreateNoteRequest\x1a\x19.notes.CreateNoteResponse\x12\x38\n\x07GetNote\x12\x15.notes.GetNoteRequest\x1a\x16.notes.GetNoteResponse\x12\x43\n\x08GetNotes\x12\x1a.notes.GetListNotesRequest\x1a\x1b.notes.GetListNotesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notes_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREATENOTEREQUEST']._serialized_start=22
  _globals['_CREATENOTEREQUEST']._serialized_end=88
  _globals['_CREATENOTERESPONSE']._serialized_start=90
  _globals['_CREATENOTERESPONSE']._serialized_end=128
  _globals['_GETNOTEREQUEST']._serialized_start=130
  _globals['_GETNOTEREQUEST']._serialized_end=164
  _globals['_GETNOTERESPONSE']._serialized_start=166
  _globals['_GETNOTERESPONSE']._serialized_end=288
  _globals['_GETLISTNOTESREQUEST']._serialized_start=290
  _globals['_GETLISTNOTESREQUEST']._serialized_end=311
  _globals['_GETLISTNOTESRESPONSE']._serialized_start=313
  _globals['_GETLISTNOTESRESPONSE']._serialized_end=374
  _globals['_NOTE']._serialized_start=377
  _globals['_NOTE']._serialized_end=577
# @@protoc_insertion_point(module_scope)
